services:
  classic-app:
    env_file:
      - .envs/lara-classic/app.env
    ports:
      - ${LARA_CLASSIC_APP_HTTP_PUBLISH_PORT}:80
      - ${LARA_CLASSIC_APP_HTTPS_PUBLISH_PORT}:443
    volumes:
      - ${DOCKER_VOLUME_ROOT_DIR}lara-classic:/var/www/html
  
  octane-app:
    env_file:
      - .envs/lara-octane/app.env
    ports:
      - ${LARA_OCTANE_APP_HTTP_PUBLISH_PORT}:80
      - ${LARA_OCTANE_APP_HTTPS_PUBLISH_PORT}:443
    volumes:
      - ${DOCKER_VOLUME_ROOT_DIR}lara-octane:/var/www/html
